<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Version>0.1.0</Version>
    <Authors>MacauMuse</Authors>
    <Product>聊天桥</Product>
  </PropertyGroup>
</Project>
